events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    charset       utf-8;

    # Mantenemos tus backends para el balanceo
    upstream flask_app {
        server viajego-backend-1:5000;
        server viajego-backend-2:5000;
    }

    # 1. REDIRECCIÓN DE HTTP A HTTPS
    # Si alguien entra por el puerto 80, lo mandamos al seguro (443)
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # 2. SERVIDOR SEGURO (HTTPS)
    server {
        listen 443 ssl;
        server_name localhost;

        # RUTAS A  CERTIFICADOS 
        ssl_certificate     /etc/nginx/certs/viajego.crt;
        ssl_certificate_key /etc/nginx/certs/viajego.key;

        # Protocolos y cifrados seguros
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # Frontend (Archivos estáticos)
        location / {
            root /var/www/html;
            index index.html;
            try_files $uri $uri/ /index.html;
            add_header Content-Type "text/html; charset=utf-8";
        }

        # API (Backend Flask)
        location /api/ {
            proxy_pass http://flask_app; # Redirige al upstream
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Avisamos a Flask que ahora estamos en HTTPS
            proxy_set_header X-Forwarded-Proto $scheme;
            
            add_header Content-Type "application/json; charset=utf-8";
        }
    }
}